[package]
name = "opencl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
defaults = ["std"]
std = []
async = ["futures"]

[dependencies]
cl-sys = "0.4"
lazy_static = "1"
cfg-if = "1"
bitflags = "1"
elor = "1"
futures = { version = "0.3", optional = true }