[package]
name = "opencl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
async = ["futures", "future-parking_lot"]

[dependencies]
cl-sys = "0.4"
lazy_static = "1"
cfg-if = "1"
bitflags = "1"
elor = "1"
parking_lot = "0.12.1"
lock_api = "0.3.4"
future-parking_lot = { version = "0.3.3", optional = true }
futures = { version = "0.3.21", optional = true }

[dev-dependencies]
tokio = { veriosn = "1", features = ["full"] }